@extends('user.layout-web2')

@section('title')
    Terms and Services - Gofans
@endsection

@section('page-title')
    Terms and Services
@endsection

@section('content')
    <div class="faq-area">
        <div class="terms-content">
            <h4 class="mb-3 border-bottom">Use of {{ env("APP_NAME") }}</h4>
            <p>
                This site is owned and operated by Le Chef Plc trading as ChefOnline (referred to as "chefonline.co.uk", "ChefOnline", "us", or "our" herein). By using chefonline.co.uk you agree to be legally bound by these terms, which shall take effect immediately on your first use of chefonline.co.uk. If you do not agree to be legally bound by all the following terms please do not access and/or use chefonline.co.uk.
            </p>
            <p>
                No material from the site may be copied, reproduced, republished, uploaded, posed, transmitted, or distributed in any way, except that you may download one copy of the materials on any single computer for your non-commercial use only, provided that you keep intact all copyright and other proprietary notices. Modification of the materials or use of the materials for any other purpose is a violation of chefonline.co.uk copyright and other proprietary rights. The use of any such material on any other web site or networked computer environment is prohibited. Except as otherwise indicated on this site and except for the trademarks, service marks and trade names of other companies that are displayed on this site, all trademarks, service marks and trade names are property of chefonline.co.uk.
            </p>
            <p>
                chefonline.co.uk may change these terms at any time by posting changes online. Please review these terms regularly to ensure you are aware of any changes made by chefonline.co.uk.
            </p>
            <p>
                Your continued use of chefonline.co.uk after changes are posted means you agree to be legally bound by these terms as updated and amended.
            </p>
            <p>
                In the event that you download any software from this, or any accompanying site, the software, including any files, images incorporated in or generated by the software, and data accompanying the software (collectively, the "Software") are non-exclusively licensed to you by chefonline.co.uk.
            </p>
            <p>
                chefonline.co.uk does not transfer title of the Software to you. chefonline.co.uk retains full and complete title to the Software, and all intellectual property rights therein. You may not sell, redistribute, decompile, reverse engineer, disassemble, or otherwise reduce the Software to a human-perceivable form.
            </p>
            <p>
                All claims, disputes or disagreements which may arise out of the interpretation, performance or in any way relating to your use of this site and any and all other chefonline.co.uk site(s), shall be submitted exclusively to the jurisdiction of the Courts of England and Wales and English law shall apply.
            </p>
            <p>
                chefonline.co.uk also assumes no responsibility, and shall not be liable for any damages to, or viruses that may infect your computer equipment or other property on account of your access to, use of, or browsing in the site or your downloading of any materials, data, text, images, video, or audio from the site.
            </p>
            <p>
                chefonline.co.uk may use anything you transmit or post for any purpose, including but not limited to reproduction, disclosure, transmission, publication, broadcast, and posting.
            </p>
            <h4 class="mb-3 border-bottom">Liablity</h4>
            <p>
                Under no circumstances, including, but not limited to, negligence, shall chefonline.co.uk be liable for any special or consequential damages that result from the use of, or the inability to use, the materials in this site, even if chefonline.co.uk or a chefonline.co.uk authorized representative has been advised of the possibility of such damages. In no event shall chefonline.co.uk have any liability to you for damages, losses and causes of action (whether in contract, tort (including, but not limited to, negligence), or otherwise) for accessing this site.
            </p>
            <h4 class="mb-3 border-bottom">Disclaimer</h4>
            <p>
                CHEFONLINE.CO.UK SHALL NOT BE LIABLE FOR ANY DAMAGES OR INJURY RESULTING FROM YOUR ACCESS TO, OR INABILITY TO ACCESS, THIS SITE, OR YOUR RELIANCE ON ANY INFORMATION PROVIDED AT THIS SITE. WITHOUT LIMITING THE FOREGOING, EVERYTHING ON THE SITE IS PROVIDED TO YOU "AS IS" WITHOUT WARRANTEE OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. CHEFONLINE.CO.UK DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE MATERIALS WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. CHEFONLINE.CO.UK DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE MATERIALS IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE. YOU (AND NOT CHEFONLINE.CO.UK) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.
            </p>
            <h3>Online Ordering</h3>
            <p>
                We reserve the right to refuse your offer should it be necessary
            </p>
            <h4 class="mb-3 border-bottom">Payment</h4>
            <ol>
                <li>chefonline.co.uk accepts the following forms of payment for online ordering:</li>
                <li>Credit / Charge cards: Visa and Mastercard are accepted.</li>
                <li>Debit Cards, such as Visa, Delta, Mastro or Switch are accepted.</li>
                <li>In the event of chefonline.co.uk needing to issue a refund we will endeavour to credit your account within 21 working days.</li>
                <li>The owner of the card used to make payment must present this card on receiving the order.</li>
            </ol>

            <div class="clearif"></div>
            <h3>Card payments are secure.</h3>
            <p>
                chefonline.co.uk do not accept cheques, American Express, Diners Club or other means of payment other than those detailed above.
            </p>
            <h3>Product</h3>
            <p>
                Although every care is taken, some products may contain nuts.
            </p>
            <h4 class="mb-3 border-bottom">Promotions and Discounts</h4>
            <p>
                When submitting your order details you may wish to offer to purchase the items specified in conjunction with a particular offer or promotion. To take advantage of this facility you will need to enter the appropriate promo code with your order details. These codes are presented on our menu and other items of promotional literature from time to time.
            </p>
            <p>
                Any such order will be subject to the specific terms and conditions of the promotion in question and will be subject to availability. We reserve the right to refuse or withdraw any chefonline.co.uk promotion or discount at any time Delivery Times
            </p>
            <p>
                Our aim is to meet a delivery window for our customers, agreed at the time of placing the order. Whilst we will do our utmost to meet this delivery time unfortunately there may be factors beyond our control that prevent us from meeting the time slot.
            </p>
            <p>
                We shall have no liability whatsoever for any delay or failure to deliver to you where such delay or failure is caused by a circumstance beyond our reasonable control. Such circumstances include, but are not limited to; • Unforeseen Traffic Delays • Accidents Causing Delays on the Service Route • Severe Weather Conditions
            </p>
            <h4 class="mb-3 border-bottom">Your Order Confirmation</h4>
            <p>
                Your Order Confirmation is a record of our agreement to deliver the products ordered and paid for in full. If someone else made the booking on your behalf, you agree that such person acted as your agent.
            </p>
            <h4 class="mb-3 border-bottom">Amendments to Orders</h4>
            <p>
                Amendments to the order or delivery time can be made no later than 1 hour prior to the start of the delivery window booked.Amendments to the content of your order can be made up to 1 Hour before the delivery window begins.
            </p>
            <p>
                Amendments to the order must be made by phoning the store you have placed the order at and quoting your order number. Your initial payment will be cancelled and a new payment raised.
            </p>
            <p>
                The delivery time slot may be altered up to 1 hour before the start of your order window. The order can only be changed to a new time slot if it is available.
            </p>
            <h4 class="mb-3 border-bottom">Cancellations</h4>
            <p>
                Orders may be cancelled in full up to 1 hour before the start of the delivery window selected. We will endeavour to issue a refund to your credit card account within 21 working days.
            </p>
            <p>
                Cancellations within 1 hour of the start of the delivery window will be charged in full.
            </p>
            <h4 class="mb-3 border-bottom">Customer Responsibilities</h4>
            <p>
                When making a booking over the Internet you must carefully check the details in the "Place Order" screen of the chefonline.co.uk website. Once you have pressed the "Place Order" button an Order Confirmation with confirmation number will be displayed.
            </p>
            <p>
                It is the customer responsibility to enter the delivery address in full to ensure the driver may locate the correct property for delivery. Failure to deliver due to incorrect address details will be charged in full.
            </p>
            <p>
                You must ensure that delivery can be made to the address during the selected window. If we are unable to make delivery at the given address in the selected time slot then we will deem the order cancelled at full cost.
            </p>
            <p>
                No rescheduling of time will be permitted.
            </p>
            <p>
                In the case of addresses that are irregular or difficult to locate, it is the responsibility of the customer to clearly mark special delivery instructions in the box required. Failure to do so may result in a delayed delivery, or the order being cancelled by chefonline.co.uk.
            </p>
            <h4 class="mb-3 border-bottom">Your Personal Data</h4>
            <p>
                You agree that personal data may be retained, used and disclosed by us and our agents for the purpose of complying with our obligations under these Terms and Conditions for delivery including, but not limited to, administering your order and complying with any legal obligations.
            </p>
            <p>
                Trade marks and Copyright
            </p>
            <p>All contents included on this site are the property of Le Chef Plc trading as chefonline.co.uk and protected by UK and European copyright laws.</p>
            <p>
                The content and software on this site may be used as either or both an information and shopping resource. Any other use including reproduction, modification, distribution, transmission or republication of the content of this service is strictly prohibited. Amendments and Waivers to these terms and conditions
            </p>
            <p>
                None of our employees, agents, or representatives, has authority to alter, modify or waive any provision of these Conditions of order.
            </p>

        </div>
    </div>
@endsection

